if(MSVC)
set(THIRD_PARTY_ROOT "" CACHE PATH "third_party install root directory")

IF(EXISTS ${THIRD_PARTY_ROOT})
    MESSAGE(STATUS "set THIRD_PARTY_ROOT to ${THIRD_PARTY_ROOT}")
ELSE()
    message( FATAL_ERROR "THIRD_PARTY_ROOT: ${THIRD_PARTY_ROOT} is not a directory." )
ENDIF()


IF(EXISTS ${THIRD_PARTY_ROOT}/include)
    SET(THIRD_PARTY_INCLUDE_DIR "${THIRD_PARTY_ROOT}/${MSVC_NAME}/include" "${THIRD_PARTY_ROOT}/include")
    include_directories(${THIRD_PARTY_INCLUDE_DIR})
    MESSAGE(STATUS "set THIRD_PARTY_INCLUDE_DIR to ${THIRD_PARTY_INCLUDE_DIR}")
ELSE()
    message( FATAL_ERROR "THIRD_PARTY_INCLUDE_DIR: ${THIRD_PARTY_INCLUDE_DIR} is not a directory." )
ENDIF()


IF(EXISTS ${THIRD_PARTY_ROOT}/lib)
    SET(THIRD_PARTY_LIBRARY_DIR "${THIRD_PARTY_ROOT}/lib/${MSVC_NAME}/${MSVC_LIB_DIR}" "${THIRD_PARTY_ROOT}/lib/${MSVC_LIB_DIR}" "${THIRD_PARTY_ROOT}/lib")

    link_directories(${THIRD_PARTY_LIBRARY_DIR})
    MESSAGE(STATUS "set THIRD_PARTY_LIBRARY_DIR to ${THIRD_PARTY_LIBRARY_DIR}")
ELSE()
    message( FATAL_ERROR "THIRD_PARTY_LIBRARY_DIR: ${THIRD_PARTY_LIBRARY_DIR} is not a directory." )
ENDIF()




endif()